# -*- coding: utf-8 -*-
"""app-VIKOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zu5nOjE_5bLmkf8EYY7NZL4WxEjpDTsE
"""

import streamlit as st
import numpy as np
import pandas as pd

# ==========================================
# CONFIGURACIÓN DE LA PÁGINA
# ==========================================
st.set_page_config(page_title="Método VIKOR", layout="wide")
st.title("Método VIKOR")
st.markdown('El método VIKOR es una herramienta matemática que ayuda a elegir la mejor opción cuando tienes varias alternativas y necesitas evaluar factores que compiten entre sí. Su objetivo principal es encontrar una "solución de compromiso", es decir, la opción que ofrezca el mejor equilibrio general, donde maximiza la utilidad grupal y minimiza el arrepentimiento individual.')

# ==========================================
# BARRA LATERAL (GLOBAL)
# ==========================================
st.sidebar.header("Valor de Utilidad grupal v")
v = st.sidebar.slider("v es el peso de la estrategia de toma de decisiones “la mayoría de los criterios”", min_value=0.0, max_value=1.0, value=0.5, step=0.05)
st.sidebar.divider()

st.sidebar.header("Pesos o Valor de importancia")
st.sidebar.write("La suma de todos tus pesos debe ser exactamente 1")
espacio_nota = st.sidebar.empty()
st.sidebar.divider()

# ==========================================
# SELECTOR DE MODO DE ENTRADA
# ==========================================
modo = st.radio("¿Cómo prefieres ingresar los datos de tu tabla?", ["Agregar manualmente los datos de mi tabla", "Subir archivo Excel (.xlsx) de mi tabla"], horizontal=True)
st.divider()

# Variables puente
X_vals = None
alternativas = []
criterios = []
pesos_auto = None

# ==========================================
# MODO 1: INGRESO MANUAL
# ==========================================
if modo == "Agregar manualmente los datos de mi tabla":
    st.write("Configura el tamaño de tu tabla dadas la cantidad de opciones y criterios de evaluación que desees. No es necesario que tu tabla tenga la misma cantidad de opciones y criterios.")
    col1, col2 = st.columns(2)
    with col1:
        num_alt = st.number_input("Número de Opciones (filas)", min_value=2, value=5, step=1)
    with col2:
        num_crit = st.number_input("Número de Criterios de evaluación (columnas)", min_value=2, value=3, step=1)

    alternativas = [f"Opción {i+1}" for i in range(num_alt)]
    criterios = [f"Criterio {j+1}" for j in range(num_crit)]

    df_vacio = pd.DataFrame(0.0, index=alternativas, columns=criterios)
    df_vacio.insert(0, "Nombre de cada Opción", alternativas)
    
    st.subheader("Llena la siguiente tabla con tus datos correspondientes")
    st.info("Esta tabla recibe el nombre de: Matriz de decisión. Haz doble clic en cualquier celda para editar el valor que le designas a cada opción dado su criterio de evaluación. No olvides agregar nombre a tus opciones.")

    # TRUCO DE MEMORIA: Evita que la tabla se borre al dar clic en el botón
    if "df_manual" not in st.session_state or st.session_state.get("prev_alt") != num_alt or st.session_state.get("prev_crit") != num_crit:
        st.session_state.df_manual = pd.DataFrame(np.zeros((num_alt, num_crit)), index=alternativas, columns=criterios)
        st.session_state.prev_alt = num_alt
        st.session_state.prev_crit = num_crit

    df_X = st.data_editor(st.session_state.df_manual, use_container_width=True, key="matriz_manual")

    # Extraemos los datos tecleados
    X_vals = df_X.values

# ==========================================
# MODO 2: SUBIR ARCHIVO EXCEL
# ==========================================
elif modo == "Subir archivo Excel (.xlsx) de mi tabla":
    st.subheader("Sube tu archivo. No olvides poner nombres a tus Opciones y Criterios de evaluación 🧐.")
    st.info("Si deseas que se agreguen automáticamente los Pesos o Valores de importancia de tus Criterios de evaluación, debes agregar una segunda hoja a tu archivo Excel y en ella debes colocar el peso de tus criterios. NOTA: debes colocar de arriba a abajo (es decir, únicamente en la columna A) el peso de tus criterios, el primer peso que agregues será considerado el peso del criterio de evaluación 1, el segundo peso que agregues será considerado el peso del criterio de evaluación 2 y así sucesivamente. Cualquier duda contactar a: [Algún correo]")
    st.info("Si deseas agregar tus Pesos manualmente sube tu archivo Excel con únicamente una Hoja que incluya tu tabla de decisión. Una vez cargado tu archivo, en el menú lateral podrás agregar manualmente tus Pesos o Valores de importancia por criterio.")
    uploaded_file = st.file_uploader("Selecciona un archivo .xlsx", type=["xlsx"])

    if uploaded_file:
        excel_obj = pd.ExcelFile(uploaded_file)

        # MATRIZ (Primera hoja)
        df_subido = pd.read_excel(uploaded_file, sheet_name=0)
        st.success(f"Tabla cargada desde la hoja: '{excel_obj.sheet_names[0]}'")
        df_editado = st.data_editor(df_subido, hide_index=True, use_container_width=True, key="matriz_excel")

        alternativas = df_editado.iloc[:, 0].astype(str).tolist()
        criterios = df_editado.columns[1:].tolist()
        num_criterios_reales = len(criterios)
        X_vals = df_editado.iloc[:, 1:].values

        # PESOS (Segunda hoja)
        if len(excel_obj.sheet_names) > 1:
            try:
                df_conf = pd.read_excel(uploaded_file, sheet_name=1, header=None)
                if df_conf.empty or len(df_conf.columns) == 0:
                    st.warning("Se detectó una segunda hoja, pero está vacía. Por favor cree la lista de pesos en la columna A.")
                else:
                    pesos_brutos = pd.to_numeric(df_conf.iloc[:, 0], errors='coerce').dropna().tolist()

                    if len(pesos_brutos) == 0:
                        st.warning("La segunda hoja no tiene números válidos. Ajusta manualmente en la barra lateral.")
                    elif len(pesos_brutos) != num_criterios_reales:
                        st.warning(f"Se detectaron {len(pesos_brutos)} pesos, pero hay {num_criterios_reales} criterios. Ajusta manualmente en la barra lateral.")
                    else:
                        suma_pesos = sum(pesos_brutos)
                        if suma_pesos < 0.999 or suma_pesos > 1.01:
                            st.warning(f"Tus pesos suman {suma_pesos:.2f} en lugar de 1.00. Ajusta manualmente en la barra lateral.")
                        else:
                            pesos_auto = pesos_brutos
                            st.success(f"Pesos obtenidos de la hoja: '{excel_obj.sheet_names[1]}'. Ve al menú lateral para definir maximizar/minimizar.")
            except Exception as e:
                st.error("Hubo un error al leer la segunda hoja. Verifica el formato.")
        else:
            st.info("No se detectó una segunda hoja. Ajusta tus pesos manualmente en la barra lateral izquierda.")

# ==========================================
# BARRA LATERAL HÍBRIDA Y LÓGICA DE CÁLCULO
# ==========================================
if X_vals is not None:
    pesos = []
    impactos = []

    for i, col in enumerate(criterios):
        st.sidebar.subheader(f"{col}")

        # 1. EL PESO
        if pesos_auto is None:
            w = st.sidebar.slider(f"Peso para {col}", 0.0, 1.0, 0.0, key=f"w_{col}")
        else:
            w = pesos_auto[i] if i < len(pesos_auto) else 0.0
            st.sidebar.info(f"**Peso asignado:** {w}")

        # 2. EL IMPACTO
        imp = st.sidebar.selectbox(f"Necesito:", ["Maximizar (+)", "Minimizar (-)"], key=f"imp_{col}")

        pesos.append(w)
        impactos.append(1 if "Maximizar" in imp else -1)

    # Lógica del contador visual
    suma_actual = sum(pesos)
    if round(suma_actual, 2) == 1.00:
        espacio_nota.success(f"Perfecto, has llegado a: {suma_actual:.2f} / 1.00")
    elif suma_actual > 1.00:
        espacio_nota.error(f"Has rebasado 1, llevas: {suma_actual:.2f} / 1.00")
    else:
        espacio_nota.warning(f"Llevas: {suma_actual:.2f} (Te faltan {1.0 - suma_actual:.2f})")

    # BOTÓN DE EJECUCIÓN
    if st.button("Obtener Ranking de la o las mejores opciones", type="primary"):

        w_array = np.array(pesos)
        beneficio_array = np.array(impactos)

        # PASO 1: Mejores y peores valores
        f_star = np.zeros(len(criterios))
        f_minus = np.zeros(len(criterios))

        for j in range(len(criterios)):
            if beneficio_array[j] == 1:
                f_star[j] = np.max(X_vals[:, j])
                f_minus[j] = np.min(X_vals[:, j])
            else:
                f_star[j] = np.min(X_vals[:, j])
                f_minus[j] = np.max(X_vals[:, j])

        divisor = f_star - f_minus
        divisor[divisor == 0] = 1e-10

        # PASO 2: Matriz F, S_i y R_i
        F = (f_star - X_vals) / divisor
        WF = F * w_array
        S = WF.sum(axis=1)
        R = WF.max(axis=1)

        # PASO 3: Índice VIKOR (Q_i)
        S_star, S_minus = S.min(), S.max()
        R_star, R_minus = R.min(), R.max()

        denom_S = (S_minus - S_star) if (S_minus - S_star) != 0 else 1e-10
        denom_R = (R_minus - R_star) if (R_minus - R_star) != 0 else 1e-10

        Q = v * (S - S_star) / denom_S + (1 - v) * (R - R_star) / denom_R

        tabla_final = pd.DataFrame({"S": S, "R": R, "Q": Q}, index=alternativas)

        # PASO 4 y 5: Ranking y Condición C1
        ranking = tabla_final.sort_values("Q")
        m = len(ranking)
        DQ = 1 / (m - 1) if m > 1 else 0

        a1 = ranking.index[0]
        a2 = ranking.index[1] if m > 1 else a1
        Q1 = ranking.iloc[0]["Q"]
        Q2 = ranking.iloc[1]["Q"] if m > 1 else Q1

        C1 = (Q2 - Q1) >= DQ

        # PASO 6: Condición C2
        mejor_S = tabla_final["S"].idxmin()
        mejor_R = tabla_final["R"].idxmin()
        C2 = (a1 == mejor_S) or (a1 == mejor_R)

        # PASO 7 y 8: Solución de compromiso
        if C1 and C2:
            compromiso = [a1]
            msg_compromiso = "Se cumplen C1 y C2. Existe una solución única."
        elif C1 and not C2:
            compromiso = [a1, a2]
            msg_compromiso = "Se cumple C1 pero NO C2. La solución de compromiso incluye las dos mejores."
        else:
            compromiso = [alt for alt in ranking.index if ranking.loc[alt, "Q"] - Q1 < DQ]
            msg_compromiso = "NO se cumple C1. Se ha generado un conjunto de soluciones de compromiso."

        # DESPLIEGUE DE RESULTADOS
        st.divider()
        st.header("Resultados VIKOR")

        col_res1, col_res2 = st.columns(2)
        with col_res1:
            st.subheader("Valores Ideales")
            df_ideales = pd.DataFrame({"f* (Mejor)": f_star, "f- (Peor)": f_minus}, index=criterios)
            st.dataframe(df_ideales.round(4), use_container_width=True)

        with col_res2:
            st.subheader("Ranking Final (Menor Q es mejor)")
            st.dataframe(ranking.round(4).style.highlight_min(subset=['Q'], color='lightgreen'), use_container_width=True)

        st.subheader("Análisis de Compromiso")
        st.write(f"- **DQ (Límite C1):** {DQ:.4f}")
        st.write(f"- **Q(a2) - Q(a1):** {(Q2 - Q1):.4f}")
        st.write(f"- **Condición C1 (Ventaja):** {'✅' if C1 else '❌'}")
        st.write(f"- **Condición C2 (Estabilidad):** {'✅' if C2 else '❌'}")

        st.info(msg_compromiso)
        st.success(f"**Solución(es) recomendada(s):** {', '.join(compromiso)}")
